dist: trusty
language: ruby
rvm:
  - 2.3.1
sudo: false

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

cache:
  bundler: true

before_install:
  - gem update --system
  - gem install bundler
